services:
  backend:
    build:
      context: ./backend
    container_name: nexatalk-backend
    env_file:
      - ./backend/.env
    expose:
      - "5000"
    depends_on:
      - mongo
      - redis
    volumes:
      - uploads_data:/app/uploads
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    container_name: nexatalk-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:7
    container_name: nexatalk-mongo
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:7-alpine
    container_name: nexatalk-redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo_data:
  uploads_data: