services:
  backend:
    build:
      context: ./backend
    container_name: nexatalk-backend
    env_file:
      - ./backend/.env
    expose:
      - "5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    container_name: nexatalk-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  mongo:
    image: mongo:7
    container_name: nexatalk-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: