export const AuditLogAction = {
  SERVER_NAME_UPDATED: "SERVER_NAME_UPDATED",
  SERVER_DESCRIPTION_UPDATED: "SERVER_DESCRIPTION_UPDATED",
  SERVER_PRIVACY_UPDATED: "SERVER_PRIVACY_UPDATED",
  SERVER_ICON_UPDATED: "SERVER_ICON_UPDATED",
  SERVER_BANNER_UPDATED: "SERVER_BANNER_UPDATED",
  SERVER_TAGS_UPDATED: "SERVER_TAGS_UPDATED",
  OWNERSHIP_TRANSFERRED: "OWNERSHIP_TRANSFERRED",
  MEMBER_PROMOTED: "MEMBER_PROMOTED",
  MEMBER_DEMOTED: "MEMBER_DEMOTED",
  MEMBER_BANNED: "MEMBER_BANNED",
  MEMBER_UNBANNED: "MEMBER_UNBANNED",
  MEMBER_KICKED: "MEMBER_KICKED",
  MEMBER_LEFT: "MEMBER_LEFT",
  INVITE_CREATED: "INVITE_CREATED",
  INVITE_REVOKED: "INVITE_REVOKED",
  CHANNEL_CREATED: "CHANNEL_CREATED",
  CHANNEL_RENAMED: "CHANNEL_RENAMED",
  CHANNEL_DELETED: "CHANNEL_DELETED",
  DIRECT_INVITE_SENT: "DIRECT_INVITE_SENT",
  DIRECT_INVITE_ACCEPTED: "DIRECT_INVITE_ACCEPTED",
  DIRECT_INVITE_REJECTED: "DIRECT_INVITE_REJECTED",
  SERVER_DELETED: "SERVER_DELETED",
} as const;

export type AuditLogActionType = typeof AuditLogAction[keyof typeof AuditLogAction];

export const AUDIT_LOG_ACTION_LABELS: Record<string, string> = {
  [AuditLogAction.SERVER_NAME_UPDATED]: "Server Name Updated",
  [AuditLogAction.SERVER_DESCRIPTION_UPDATED]: "Server Description Updated",
  [AuditLogAction.SERVER_PRIVACY_UPDATED]: "Server Privacy Updated",
  [AuditLogAction.SERVER_ICON_UPDATED]: "Server Icon Updated",
  [AuditLogAction.SERVER_BANNER_UPDATED]: "Server Banner Updated",
  [AuditLogAction.SERVER_TAGS_UPDATED]: "Server Tags Updated",
  [AuditLogAction.OWNERSHIP_TRANSFERRED]: "Ownership Transferred",
  [AuditLogAction.MEMBER_PROMOTED]: "Member Promoted",
  [AuditLogAction.MEMBER_DEMOTED]: "Member Demoted",
  [AuditLogAction.MEMBER_BANNED]: "Member Banned",
  [AuditLogAction.MEMBER_UNBANNED]: "Member Unbanned",
  [AuditLogAction.MEMBER_KICKED]: "Member Kicked",
  [AuditLogAction.MEMBER_LEFT]: "Member Left Server",
  [AuditLogAction.INVITE_CREATED]: "Invite Created",
  [AuditLogAction.INVITE_REVOKED]: "Invite Revoked",
  [AuditLogAction.CHANNEL_CREATED]: "Channel Created",
  [AuditLogAction.CHANNEL_RENAMED]: "Channel Renamed",
  [AuditLogAction.CHANNEL_DELETED]: "Channel Deleted",
  [AuditLogAction.DIRECT_INVITE_SENT]: "Direct Invite Sent",
  [AuditLogAction.DIRECT_INVITE_ACCEPTED]: "Direct Invite Accepted",
  [AuditLogAction.DIRECT_INVITE_REJECTED]: "Direct Invite Rejected",
  [AuditLogAction.SERVER_DELETED]: "Server Deleted",
};
